const drinks = {
    title: {
        hu: 'Itallap',
        en: 'Drinks Menu',
        de: 'Getränkekarte',
    },
    categories: [
        {
            hu: 'Üdítők',
            en: 'Soft drinks',
            de: 'Erfrischungsgetränke',
            images: ['/media/drinks/menu/uditok.webp'],
            items: [
                {
                    hu: 'Coca-Cola szénsavas üdítők 0,25 l (Cola, Cola Zero, Sprite, Fanta, Kinley tonic, Kinley gyömbér)',
                    en: 'Coca-Cola carbonated soft drinks 0,25 l (Cola, Cola Zero, Sprite, Fanta, Kinley tonic, Kinley ginger)',
                    de: 'Coca-Cola kohlensäurehaltige Erfrischungsgetränke 0,25 l (Cola, Cola Zero, Sprite, Fanta, Kinley Tonic, Kinley Ingwer)',
                    prices: ['690 Ft'],
                },
                {
                    hu: 'Römerquelle 0,75 l (mentes, savas)',
                    en: 'Römerquelle 0,75 l (still, sparkling)',
                    de: 'Römerquelle 0,75 l (still, sprudelnd)',
                    prices: ['1.400 Ft'],
                },
                {
                    hu: 'Römerquelle 0,33 l (mentes, savas)',
                    en: 'Römerquelle 0,33 l (still, sparkling)',
                    de: 'Römerquelle 0,33 l (still, sprudelnd)',
                    prices: ['790 Ft'],
                },
                {
                    hu: 'Cappy 0,25 l (narancs, alma, őszibarack)',
                    en: 'Cappy 0,25 l (orange, apple, peach)',
                    de: 'Cappy 0,25 l (Orange, Apfel, Pfirsich)',
                    prices: ['850 Ft'],
                },
                {
                    hu: 'Spezi 0,5 l',
                    en: 'Spezi 0,5 l',
                    de: 'Spezi 0,5 l',
                    prices: ['1.380 Ft'],
                },
                {
                    hu: 'Almafröccs 0,5 l',
                    en: 'Apple spritzer 0,5 l',
                    de: 'Apfelschorle 0,5 l',
                    prices: ['1.190 Ft'],
                },
                {
                    hu: 'Limonádé 0,5 l (több ízben)',
                    en: 'Lemonade 0,5 l (various flavors)',
                    de: 'Limonade 0,5 l (verschiedene Sorten)',
                    prices: ['1.550 Ft'],
                },
                {
                    hu: 'Limonádé 1 l (több ízben)',
                    en: 'Lemonade 1 l (various flavors)',
                    de: 'Limonade 1 l (verschiedene Sorten)',
                    prices: ['2.750 Ft'],
                },
                {
                    hu: 'Házi Citromos Jegestea 0,4 l',
                    en: 'Homemade lemon iced tea 0,4 l',
                    de: 'Hausgemachter Zitronen-Eistee 0,4 l',
                    prices: ['1.200 Ft'],
                },
                {
                    hu: 'Fever Tree 0,2 l (több ízben)',
                    en: 'Fever Tree 0,2 l (various flavors)',
                    de: 'Fever Tree 0,2 l (verschiedene Sorten)',
                    prices: ['1.300 Ft'],
                },
                {
                    hu: 'Three Cents 0,2 l (több ízben)',
                    en: 'Three Cents 0,2 l (various flavors)',
                    de: 'Three Cents 0,2 l (verschiedene Sorten)',
                    prices: ['1.300 Ft'],
                },
                {
                    hu: 'Szóda 0,1 l',
                    en: 'Soda 0,1 l',
                    de: 'Soda 0,1 l',
                    prices: ['170 Ft'],
                },
            ],
        },
        {
            hu: 'Energiaital',
            en: 'Energy drinks',
            de: 'Energydrinks',
            images: ['/media/drinks/menu/energiaital.webp'],
            items: [
                {
                    hu: 'Red Bull Energy Drink',
                    en: 'Red Bull Energy Drink',
                    de: 'Red Bull Energy Drink',
                    prices: ['950 Ft'],
                },
                {
                    hu: 'Red Bull Sugarfree',
                    en: 'Red Bull Sugarfree',
                    de: 'Red Bull Sugarfree',
                    prices: [],
                },
                {
                    hu: 'Red Bull White Edition',
                    en: 'Red Bull White Edition',
                    de: 'Red Bull White Edition',
                    prices: [],
                },
                {
                    hu: 'Red Bull editions',
                    en: 'Red Bull editions',
                    de: 'Red Bull Editions',
                    prices: [],
                },
                {
                    hu: '(Az energiaital fogyasztása 18 éven aluliak számára nem engedélyezett.)',
                    en: '(The consumption of energy drinks is not permitted for persons under 18 years of age.)',
                    de: '(Der Konsum von Energydrinks ist für Personen unter 18 Jahren nicht erlaubt.)',
                    prices: [],
                },
            ],
        },
        {
            hu: 'Kávé',
            en: 'Coffee',
            de: 'Kaffee',
            images: ['/media/drinks/menu/whiskey_2.webp'],
            items: [
                {
                    hu: 'Ristretto (2 cl rövid kávé)',
                    en: 'Ristretto (2 cl short coffee)',
                    de: 'Ristretto (2 cl kurzer Kaffee)',
                    prices: ['690 Ft'],
                },
                {
                    hu: 'Espresso (3-4 cl rövid kávé)',
                    en: 'Espresso (3-4 cl short coffee)',
                    de: 'Espresso (3-4 cl kurzer Kaffee)',
                    prices: ['690 Ft'],
                },
                {
                    hu: 'Doppio (dupla eszpresszó)',
                    en: 'Doppio (double espresso)',
                    de: 'Doppio (doppelter Espresso)',
                    prices: ['1.200 Ft'],
                },
                {
                    hu: 'Lungo (8 – 9 cl)',
                    en: 'Lungo (8 – 9 cl)',
                    de: 'Lungo (8 – 9 cl)',
                    prices: ['790 Ft'],
                },
                {
                    hu: 'Espresso Macchiato (espresso, tejhab)',
                    en: 'Espresso Macchiato (espresso, milk foam)',
                    de: 'Espresso Macchiato (Espresso, Milchschaum)',
                    prices: ['790 Ft'],
                },
                {
                    hu: 'Cappuccino (espresso, tej, tejhab)',
                    en: 'Cappuccino (espresso, milk, milk foam)',
                    de: 'Cappuccino (Espresso, Milch, Milchschaum)',
                    prices: ['890 Ft'],
                },
                {
                    hu: 'Latte Macchiato (espresso, tej, tejhab)',
                    en: 'Latte Macchiato (espresso, milk, milk foam)',
                    de: 'Latte Macchiato (Espresso, Milch, Milchschaum)',
                    prices: ['990 Ft'],
                },
                {
                    hu: 'Presso tonic (espresso, jég, tonic)',
                    en: 'Presso tonic (espresso, ice, tonic)',
                    de: 'Presso Tonic (Espresso, Eis, Tonic)',
                    prices: ['1.290 Ft'],
                },
                {
                    hu: 'Jeges kávé (espresso, tej, fagylalt, tejszínhab)',
                    en: 'Iced coffee (espresso, milk, ice cream, whipped cream)',
                    de: 'Eiskaffee (Espresso, Milch, Eis, Schlagsahne)',
                    prices: ['1.590 Ft'],
                },
                {
                    hu: 'Forró csoki',
                    en: 'Hot chocolate',
                    de: 'Heiße Schokolade',
                    prices: ['990 Ft'],
                },
                {
                    hu: 'Szálas Tea',
                    en: 'Loose-leaf tea',
                    de: 'Loser Tee',
                    prices: ['1.390 Ft'],
                },
                {
                    hu: 'Növényi tejjel bármelyik ital',
                    en: 'Any drink with plant-based milk',
                    de: 'Jedes Getränk mit Pflanzenmilch',
                    prices: ['+ 200 Ft'],
                },
                {
                    hu: '+ Méz',
                    en: '+ Honey',
                    de: '+ Honig',
                    prices: ['+ 200 Ft'],
                },
            ],
        },
        {
            hu: 'Csapolt sörök',
            en: 'Draft beer',
            de: 'Fassbier',
            images: ['/media/drinks/menu/csapolt_sorok.webp', '/media/drinks/menu/csapolt_sorok_2.webp'],
            items: [
                {
                    hu: 'Paulaner Original Münchner Hell (lager)',
                    en: 'Paulaner Original Münchner Hell (lager)',
                    de: 'Paulaner Original Münchner Hell (Lager)',
                    prices: ['1.100 Ft / 0,3 l', '1.700 Ft / 0,5 l'],
                },
                {
                    hu: 'Paulaner Hefe-Weissbier (szűretlen búza)',
                    en: 'Paulaner Hefe-Weissbier (unfiltered wheat)',
                    de: 'Paulaner Hefe-Weissbier (ungefilterter Weizen)',
                    prices: ['1.100 Ft / 0,3 l', '1.700 Ft / 0,5 l'],
                },
                {
                    hu: 'Paulaner IPA',
                    en: 'Paulaner IPA',
                    de: 'Paulaner IPA',
                    prices: ['1.200 Ft / 0,3 l', '1.900 Ft / 0,5 l'],
                },
                {
                    hu: 'Heineken',
                    en: 'Heineken',
                    de: 'Heineken',
                    prices: ['1.000 Ft / 0,25 l', '1.400 Ft / 0,5 l'],
                },
                {
                    hu: 'Birra Moretti',
                    en: 'Birra Moretti',
                    de: 'Birra Moretti',
                    prices: ['1.000 Ft / 0,3 l', '1.400 Ft / 0,5 l'],
                },
                {
                    hu: 'Mort Subite',
                    en: 'Mort Subite',
                    de: 'Mort Subite',
                    prices: ['1.200 Ft / 0,25 l', '1.600 Ft / 0,4 l'],
                },
            ],
        },
        {
            hu: 'Üveges sörök',
            en: 'Bottled beer',
            de: 'Flaschenbier',
            images: ['/media/drinks/menu/csapolt_sorok_2.webp'],
            items: [
                {
                    hu: 'Paulaner Salvator (buplabak barna) 0,5 l',
                    en: 'Paulaner Salvator (buplabak brown) 0,5 l',
                    de: 'Paulaner Salvator (buplabak dunkel) 0,5 l',
                    prices: ['1.700 Ft'],
                },
                {
                    hu: 'Paulaner Orig. Münchner Lager alkoholmentes 0,5 l',
                    en: 'Paulaner Orig. Münchner Lager non-alcoholic 0,5 l',
                    de: 'Paulaner Orig. Münchner Lager alkoholfrei 0,5 l',
                    prices: ['1.200 Ft'],
                },
                {
                    hu: 'Paulaner Hefe-Weissbier alkoholmentes 0,5 l',
                    en: 'Paulaner Hefe-Weissbier non-alcoholic 0,5 l',
                    de: 'Paulaner Hefe-Weissbier alkoholfrei 0,5 l',
                    prices: ['1.200 Ft'],
                },
                {
                    hu: 'Paulaner Weissbier Zitrone alkoholmentes 0,33 l',
                    en: 'Paulaner Weissbier Zitrone non-alcoholic 0,33 l',
                    de: 'Paulaner Weissbier Zitrone alkoholfrei 0,33 l',
                    prices: ['1.050 Ft'],
                },
                {
                    hu: 'Heineken 0% alkoholmentes 0,33 l',
                    en: 'Heineken 0% non-alcoholic 0,33 l',
                    de: 'Heineken 0% alkoholfrei 0,33 l',
                    prices: ['1.050 Ft'],
                },
            ],
        },
        {
            hu: 'Whiskey',
            en: 'Whiskey',
            de: 'Whiskey',
            images: ['/media/drinks/menu/whiskey.webp', '/media/drinks/menu/whiskey_2.webp', '/media/drinks/menu/whiskey_3.webp'],
            items: [
                {
                    hu: 'Glenmorangie 4 cl',
                    en: 'Glenmorangie 4 cl',
                    de: 'Glenmorangie 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Glenlivet 12 yo 4 cl',
                    en: 'Glenlivet 12 yo 4 cl',
                    de: 'Glenlivet 12 yo 4 cl',
                    prices: ['2.900 Ft'],
                },
                {
                    hu: 'Highland Park 12 yo 4 cl',
                    en: 'Highland Park 12 yo 4 cl',
                    de: 'Highland Park 12 yo 4 cl',
                    prices: ['2.700 Ft'],
                },
                {
                    hu: 'Johnny Walker Black Label 4 cl',
                    en: 'Johnny Walker Black Label 4 cl',
                    de: 'Johnny Walker Black Label 4 cl',
                    prices: ['2.000 Ft'],
                },
                {
                    hu: 'Johnny Walker Blue Label 4 cl',
                    en: 'Johnny Walker Blue Label 4 cl',
                    de: 'Johnny Walker Blue Label 4 cl',
                    prices: ['9.900 Ft'],
                },
                {
                    hu: 'Lagavulin 8 yo 4 cl',
                    en: 'Lagavulin 8 yo 4 cl',
                    de: 'Lagavulin 8 yo 4 cl',
                    prices: ['4.950 Ft'],
                },
                {
                    hu: 'Laphroaig 4 cl',
                    en: 'Laphroaig 4 cl',
                    de: 'Laphroaig 4 cl',
                    prices: ['2.900 Ft'],
                },
                {
                    hu: 'Ledaig 10 yo 4 cl',
                    en: 'Ledaig 10 yo 4 cl',
                    de: 'Ledaig 10 yo 4 cl',
                    prices: ['2.900 Ft'],
                },
                {
                    hu: 'Macallan 12 yo Double Cask 4 cl',
                    en: 'Macallan 12 yo Double Cask 4 cl',
                    de: 'Macallan 12 yo Double Cask 4 cl',
                    prices: ['4.800 Ft'],
                },
                {
                    hu: 'Oban Malt 14 4 cl',
                    en: 'Oban Malt 14 4 cl',
                    de: 'Oban Malt 14 4 cl',
                    prices: ['4.900 Ft'],
                },
                {
                    hu: 'Scapa 10 yo 4 cl',
                    en: 'Scapa 10 yo 4 cl',
                    de: 'Scapa 10 yo 4 cl',
                    prices: ['3.900 Ft'],
                },
                {
                    hu: 'Talisker 10 yo 4 cl',
                    en: 'Talisker 10 yo 4 cl',
                    de: 'Talisker 10 yo 4 cl',
                    prices: ['3.100 Ft'],
                },
                {
                    hu: "Jack Daniel's 4 cl",
                    en: "Jack Daniel's 4 cl",
                    de: "Jack Daniel's 4 cl",
                    prices: ['1.600 Ft'],
                },
                {
                    hu: 'Jack Daniels Gentleman Jack 4 cl',
                    en: 'Jack Daniels Gentleman Jack 4 cl',
                    de: 'Jack Daniels Gentleman Jack 4 cl',
                    prices: ['2.000 Ft'],
                },
                {
                    hu: "Jack Daniel's Single Barrel 4 cl",
                    en: "Jack Daniel's Single Barrel 4 cl",
                    de: "Jack Daniel's Single Barrel 4 cl",
                    prices: ['2.500 Ft'],
                },
                {
                    hu: "Jack Daniel's Sinatra 4 cl",
                    en: "Jack Daniel's Sinatra 4 cl",
                    de: "Jack Daniel's Sinatra 4 cl",
                    prices: ['5.900 Ft'],
                },
                {
                    hu: "Maker's Mark 4 cl",
                    en: "Maker's Mark 4 cl",
                    de: "Maker's Mark 4 cl",
                    prices: ['1.900 Ft'],
                },
                {
                    hu: 'Woodford Reserve 4 cl',
                    en: 'Woodford Reserve 4 cl',
                    de: 'Woodford Reserve 4 cl',
                    prices: ['2.400 Ft'],
                },
                {
                    hu: 'Bushmills Black Bush 4 cl',
                    en: 'Bushmills Black Bush 4 cl',
                    de: 'Bushmills Black Bush 4 cl',
                    prices: ['1.900 Ft'],
                },
                {
                    hu: 'Jameson 4 cl',
                    en: 'Jameson 4 cl',
                    de: 'Jameson 4 cl',
                    prices: ['1.500 Ft'],
                },
                {
                    hu: 'Teeling Single Malt 4 cl',
                    en: 'Teeling Single Malt 4 cl',
                    de: 'Teeling Single Malt 4 cl',
                    prices: ['2.900 Ft'],
                },
                {
                    hu: 'Hibiki Harmony',
                    en: 'Hibiki Harmony',
                    de: 'Hibiki Harmony',
                    prices: ['5.900 Ft'],
                },
                {
                    hu: 'Nikka from the Barrel',
                    en: 'Nikka from the Barrel',
                    de: 'Nikka from the Barrel',
                    prices: ['2.890 Ft'],
                },
                {
                    hu: 'Suntory The Chita',
                    en: 'Suntory The Chita',
                    de: 'Suntory The Chita',
                    prices: ['3.750 Ft'],
                },
            ],
        },
        {
            hu: 'Rum',
            en: 'Rum',
            de: 'Rum',
            images: ['/media/drinks/menu/whiskey_3.webp'],
            items: [
                {
                    hu: 'Bumbu 4 cl',
                    en: 'Bumbu 4 cl',
                    de: 'Bumbu 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Dictator 12 yo 4 cl',
                    en: 'Dictator 12 yo 4 cl',
                    de: 'Dictator 12 yo 4 cl',
                    prices: ['2.800 Ft'],
                },
                {
                    hu: 'Dictador Game Changer 4 cl',
                    en: 'Dictador Game Changer 4 cl',
                    de: 'Dictador Game Changer 4 cl',
                    prices: ['5.900 Ft'],
                },
                {
                    hu: 'Diplomatico exclusiva 4 cl',
                    en: 'Diplomatico exclusiva 4 cl',
                    de: 'Diplomatico exclusiva 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Don Papa 4 cl',
                    en: 'Don Papa 4 cl',
                    de: 'Don Papa 4 cl',
                    prices: ['3.500 Ft'],
                },
                {
                    hu: 'Don Papa Alon 4 cl',
                    en: 'Don Papa Alon 4 cl',
                    de: 'Don Papa Alon 4 cl',
                    prices: ['3.500 Ft'],
                },
                {
                    hu: 'Don Papa Baroko 4 cl',
                    en: 'Don Papa Baroko 4 cl',
                    de: 'Don Papa Baroko 4 cl',
                    prices: ['3.500 Ft'],
                },
                {
                    hu: 'Equiano 4 cl',
                    en: 'Equiano 4 cl',
                    de: 'Equiano 4 cl',
                    prices: ['2.750 Ft'],
                },
                {
                    hu: 'Havana Club 15 yo 4 cl',
                    en: 'Havana Club 15 yo 4 cl',
                    de: 'Havana Club 15 yo 4 cl',
                    prices: ['8.490 Ft'],
                },
                {
                    hu: 'Planteray XO 4 cl',
                    en: 'Planteray XO 4 cl',
                    de: 'Planteray XO 4 cl',
                    prices: ['3.000 Ft'],
                },
                {
                    hu: "The Demon's Share 6 yo 4 cl",
                    en: "The Demon's Share 6 yo 4 cl",
                    de: "The Demon's Share 6 yo 4 cl",
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Zacapa 23 4 cl',
                    en: 'Zacapa 23 4 cl',
                    de: 'Zacapa 23 4 cl',
                    prices: ['3.800 Ft'],
                },
            ],
        },
        {
            hu: 'Gin',
            en: 'Gin',
            de: 'Gin',
            images: ['/media/drinks/menu/gin.webp', '/media/drinks/menu/gin_2.webp'],
            items: [
                {
                    hu: 'Árpád Mála Gin 4 cl',
                    en: 'Árpád Mála Gin 4 cl',
                    de: 'Árpád Mála Gin 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: "Bobby's Dry Gin 4 cl",
                    en: "Bobby's Dry Gin 4 cl",
                    de: "Bobby's Dry Gin 4 cl",
                    prices: ['2.300 Ft'],
                },
                {
                    hu: 'Bombay 4 cl',
                    en: 'Bombay 4 cl',
                    de: 'Bombay 4 cl',
                    prices: ['2.000 Ft'],
                },
                {
                    hu: 'Brockmans Premium Gin 4 cl',
                    en: 'Brockmans Premium Gin 4 cl',
                    de: 'Brockmans Premium Gin 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Bulldog 4 cl',
                    en: 'Bulldog 4 cl',
                    de: 'Bulldog 4 cl',
                    prices: ['2.000 Ft'],
                },
                {
                    hu: 'Copperhead Black Batch gin 4 cl',
                    en: 'Copperhead Black Batch gin 4 cl',
                    de: 'Copperhead Black Batch Gin 4 cl',
                    prices: ['3.300 Ft'],
                },
                {
                    hu: "Hendrick's 4 cl",
                    en: "Hendrick's 4 cl",
                    de: "Hendrick's 4 cl",
                    prices: ['2.600 Ft'],
                },
                {
                    hu: "Hendrick's Grand Cabaret 4 cl",
                    en: "Hendrick's Grand Cabaret 4 cl",
                    de: "Hendrick's Grand Cabaret 4 cl",
                    prices: ['3.000 Ft'],
                },
                {
                    hu: "Hendrick's Oasium 4 cl",
                    en: "Hendrick's Oasium 4 cl",
                    de: "Hendrick's Oasium 4 cl",
                    prices: ['3.000 Ft'],
                },
                {
                    hu: "June by G'Vine (Royal Pear/Watermelon) 4 cl",
                    en: "June by G'Vine (Royal Pear/Watermelon) 4 cl",
                    de: "June by G'Vine (Royal Pear/Watermelon) 4 cl",
                    prices: ['2.300 Ft'],
                },
                {
                    hu: 'J.Rose Dry 4 cl',
                    en: 'J.Rose Dry 4 cl',
                    de: 'J.Rose Dry 4 cl',
                    prices: ['3.900 Ft'],
                },
                {
                    hu: 'Malfy (Con Limone/Con Arancia/Rosa) 4 cl',
                    en: 'Malfy (Con Limone/Con Arancia/Rosa) 4 cl',
                    de: 'Malfy (Con Limone/Con Arancia/Rosa) 4 cl',
                    prices: ['2.100 Ft'],
                },
                {
                    hu: 'Monkey 47 4 cl',
                    en: 'Monkey 47 4 cl',
                    de: 'Monkey 47 4 cl',
                    prices: ['3.600 Ft'],
                },
                {
                    hu: 'Mrs Millicent Gin 4 cl',
                    en: 'Mrs Millicent Gin 4 cl',
                    de: 'Mrs Millicent Gin 4 cl',
                    prices: ['3.100 Ft'],
                },
                {
                    hu: 'Roku Gin 4 cl',
                    en: 'Roku Gin 4 cl',
                    de: 'Roku Gin 4 cl',
                    prices: ['2.600 Ft'],
                },
                {
                    hu: 'Tanqueray Gin 4 cl',
                    en: 'Tanqueray Gin 4 cl',
                    de: 'Tanqueray Gin 4 cl',
                    prices: ['2.200 Ft'],
                },
                {
                    hu: 'Tanqueray Flor de Sevilla Gin 4 cl',
                    en: 'Tanqueray Flor de Sevilla Gin 4 cl',
                    de: 'Tanqueray Flor de Sevilla Gin 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Tanqueray Zero (alkoholmentes) 4 cl',
                    en: 'Tanqueray Zero (alcohol-free) 4 cl',
                    de: 'Tanqueray Zero (alkoholfrei) 4 cl',
                    prices: ['1.600 Ft'],
                },
                {
                    hu: 'The Botanist 4 cl',
                    en: 'The Botanist 4 cl',
                    de: 'The Botanist 4 cl',
                    prices: ['2.700 Ft'],
                },
            ],
        },
        {
            hu: 'Vodka',
            en: 'Vodka',
            de: 'Wodka',
            images: ['/media/drinks/menu/vodka.webp'],
            items: [
                {
                    hu: 'Beluga 4 cl',
                    en: 'Beluga 4 cl',
                    de: 'Beluga 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Belvedere 4 cl',
                    en: 'Belvedere 4 cl',
                    de: 'Belvedere 4 cl',
                    prices: ['2.600 Ft'],
                },
                {
                    hu: 'Ciroc 4 cl',
                    en: 'Ciroc 4 cl',
                    de: 'Ciroc 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Ciroc Mango 4 cl',
                    en: 'Ciroc Mango 4 cl',
                    de: 'Ciroc Mango 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Ciroc Red Berry 4 cl',
                    en: 'Ciroc Red Berry 4 cl',
                    de: 'Ciroc Red Berry 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Haku 4 cl',
                    en: 'Haku 4 cl',
                    de: 'Haku 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Grey Goose 4 cl',
                    en: 'Grey Goose 4 cl',
                    de: 'Grey Goose 4 cl',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Russian Standard Imperia 4 cl',
                    en: 'Russian Standard Imperia 4 cl',
                    de: 'Russian Standard Imperia 4 cl',
                    prices: ['2.600 Ft'],
                },
            ],
        },
        {
            hu: 'Párlatok / Pálinka',
            en: 'Spirits / Pálinka',
            de: 'Edelbrände / Pálinka',
            images: ['/media/drinks/menu/gin_2.webp'],
            items: [
                {
                    hu: 'Árpád Pálinkák 4 cl (Cigánymeggy | Irsai Olivér | Kajszibarack | Lepotica Szilva)',
                    en: 'Árpád Pálinkás 4 cl (Cigánymeggy sour cherry | Irsai Olivér grape | apricot | Lepotica plum)',
                    de: 'Árpád Pálinkás 4 cl (Cigánymeggy-Sauerkirsche | Irsai Olivér-Traube | Aprikose | Lepotica-Pflaume)',
                    prices: ['2.700 Ft'],
                },
                {
                    hu: 'Árpád Pálinkák 4 cl (Gyömbér | Mandarin | Birs)',
                    en: 'Árpád Pálinkás 4 cl (ginger | mandarin | quince)',
                    de: 'Árpád Pálinkás 4 cl (Ingwer | Mandarine | Quitte)',
                    prices: ['3.100 Ft'],
                },
            ],
        },
        {
            hu: 'Tequila',
            en: 'Tequila',
            de: 'Tequila',
            images: ['/media/drinks/menu/vodka.webp'],
            items: [
                {
                    hu: 'Patron Reposado 4 cl',
                    en: 'Patron Reposado 4 cl',
                    de: 'Patron Reposado 4 cl',
                    prices: ['3.900 Ft'],
                },
                {
                    hu: 'Patron Silver 4 cl',
                    en: 'Patron Silver 4 cl',
                    de: 'Patron Silver 4 cl',
                    prices: ['2.950 Ft'],
                },
            ],
        },
        {
            hu: 'Keserű | Likőr | Vermuth',
            en: 'Bitters | Liqueurs | Vermouth',
            de: 'Bittere | Liköre | Wermut',
            images: ['/media/drinks/menu/keseru.webp'],
            items: [
                {
                    hu: 'Unicum 4 cl',
                    en: 'Unicum 4 cl',
                    de: 'Unicum 4 cl',
                    prices: ['1.600 Ft'],
                },
                {
                    hu: 'Unicum Riserva 4 cl',
                    en: 'Unicum Riserva 4 cl',
                    de: 'Unicum Riserva 4 cl',
                    prices: ['2.100 Ft'],
                },
                {
                    hu: 'Unicum Trezor 4 cl',
                    en: 'Unicum Trezor 4 cl',
                    de: 'Unicum Trezor 4 cl',
                    prices: ['6.900 Ft'],
                },
                {
                    hu: 'Jägermeister (Original, Orange) 4 cl',
                    en: 'Jägermeister (Original, Orange) 4 cl',
                    de: 'Jägermeister (Original, Orange) 4 cl',
                    prices: ['1.600 Ft'],
                },
                {
                    hu: "Bailey's 4 cl",
                    en: "Bailey's 4 cl",
                    de: "Bailey's 4 cl",
                    prices: ['1.600 Ft'],
                },
                {
                    hu: 'Campari 8 cl',
                    en: 'Campari 8 cl',
                    de: 'Campari 8 cl',
                    prices: ['1.450 Ft'],
                },
                {
                    hu: 'Luxardo Limoncello 4 cl',
                    en: 'Luxardo Limoncello 4 cl',
                    de: 'Luxardo Limoncello 4 cl',
                    prices: ['1.500 Ft'],
                },
                {
                    hu: 'Martini Fiero 8 cl',
                    en: 'Martini Fiero 8 cl',
                    de: 'Martini Fiero 8 cl',
                    prices: ['1.200 Ft'],
                },
                {
                    hu: 'Tatratea Kókusz 22%, Citrus 32% Hibiszkusz-Vörös tea 37%',
                    en: 'Tatratea Coconut 22%, Citrus 32% Hibiscus-Red tea 37%',
                    de: 'Tatratea Kokos 22%, Zitrus 32% Hibiskus-Rottee 37%',
                    prices: ['1.500 Ft'],
                },
                {
                    hu: 'Tatratea Őszibarack 42%',
                    en: 'Tatratea Peach 42%',
                    de: 'Tatratea Pfirsich 42%',
                    prices: ['1.600 Ft'],
                },
                {
                    hu: 'Tatratea Eredeti 52%',
                    en: 'Tatratea Original 52%',
                    de: 'Tatratea Original 52%',
                    prices: ['1.700 Ft'],
                },
                {
                    hu: 'Tatratea Erdei gyümölcs 62% Alma-körte 67%, Betyár 72%',
                    en: 'Tatratea Forest fruit 62% Apple-pear 67%, Betyár 72%',
                    de: 'Tatratea Waldfrucht 62% Apfel-Birne 67%, Betyár 72%',
                    prices: ['1.900 Ft'],
                },
            ],
        },
        {
            hu: 'Cognac',
            en: 'Cognac',
            de: 'Cognac',
            images: ['/media/drinks/menu/whiskey.webp'],
            items: [
                {
                    hu: 'Hennessy VS 4 cl',
                    en: 'Hennessy VS 4 cl',
                    de: 'Hennessy VS 4 cl',
                    prices: ['2.400 Ft'],
                },
                {
                    hu: 'Hennessy VSOP 4 cl',
                    en: 'Hennessy VSOP 4 cl',
                    de: 'Hennessy VSOP 4 cl',
                    prices: ['3.900 Ft'],
                },
                {
                    hu: 'Meukow XO 4 cl',
                    en: 'Meukow XO 4 cl',
                    de: 'Meukow XO 4 cl',
                    prices: ['5.900 Ft'],
                },
            ],
        },
        {
            hu: 'Bottle service',
            en: 'Bottle service',
            de: 'Bottle Service',
            images: ['/media/drinks/menu/bottle_service.webp'],
            items: [
                {
                    hu: 'Grey Goose 1 l + 6 db Red Bull termék',
                    en: 'Grey Goose 1 l + 6 pcs Red Bull product',
                    de: 'Grey Goose 1 l + 6 Stk. Red Bull Produkt',
                    prices: ['50.000 Ft'],
                },
                {
                    hu: "Hendrick's 0,7 l + 6 db Three Cents termék",
                    en: "Hendrick's 0,7 l + 6 pcs Three Cents product",
                    de: "Hendrick's 0,7 l + 6 Stk. Three Cents Produkt",
                    prices: ['36.000 Ft'],
                },
                {
                    hu: "Jack Daniel's 1 l + 6 db Coca Cola termék",
                    en: "Jack Daniel's 1 l + 6 pcs Coca Cola product",
                    de: "Jack Daniel's 1 l + 6 Stk. Coca Cola Produkt",
                    prices: ['32.000 Ft'],
                },
                {
                    hu: 'Diplomatico Exclusiva 0,7 l + 6 db Coca Cola termék',
                    en: 'Diplomatico Exclusiva 0,7 l + 6 pcs Coca Cola product',
                    de: 'Diplomatico Exclusiva 0,7 l + 6 Stk. Coca Cola Produkt',
                    prices: ['35.000 Ft'],
                },
                {
                    hu: 'Az árak forintban értendők, az ÁFA-t tartalmazzák. Az árainkhoz 10 % felszolgálási díjat számolunk fel. Utolsó rendelés felvétele zárás előtt fél órával.',
                    en: 'All prices are subject to additional 10% service charge. Prices are in HUF and include the VAT. Last orders half an hour before closing time.',
                    de: 'Alle Preise verstehen sich zuzüglich 10 % Bedienungsgeld. Unsere Preise sind in HUF und beihalten den mWS. Letzte Bestellung 30 Minuten vor Sperrstunde.',
                    prices: [],
                },
            ],
        },
        {
            hu: 'Spritz kínálatunk',
            en: 'Our spritz selection',
            de: 'Unsere Spritz-Auswahl',
            images: ['/media/drinks/menu/keseru.webp'],
            items: [
                {
                    hu: 'Epres Campari Spritz',
                    en: 'Strawberry Campari Spritz',
                    de: 'Erdbeer-Campari-Spritz',
                    prices: ['2.900 Ft'],
                },
                {
                    hu: 'Aperol Spritz',
                    en: 'Aperol Spritz',
                    de: 'Aperol Spritz',
                    prices: ['2.900 Ft'],
                },
                {
                    hu: 'Limoncello Spritz',
                    en: 'Limoncello Spritz',
                    de: 'Limoncello Spritz',
                    prices: ['2.900 Ft'],
                },
                {
                    hu: 'St. Germain Hugo',
                    en: 'St. Germain Hugo',
                    de: 'St. Germain Hugo',
                    prices: ['2.900 Ft'],
                },
            ],
        },
        {
            hu: 'Koktél kínálatunk',
            en: 'Our cocktail selection',
            de: 'Unsere Cocktail-Auswahl',
            images: ['/media/drinks/menu/gin.webp'],
            items: [
                {
                    hu: 'Long Island Iced Tea',
                    en: 'Long Island Iced Tea',
                    de: 'Long Island Iced Tea',
                    prices: ['3.990 Ft'],
                },
                {
                    hu: 'Cuba Libre',
                    en: 'Cuba Libre',
                    de: 'Cuba Libre',
                    prices: ['2.500 Ft'],
                },
                {
                    hu: 'Negroni',
                    en: 'Negroni',
                    de: 'Negroni',
                    prices: ['2.800 Ft'],
                },
                {
                    hu: 'Mojito',
                    en: 'Mojito',
                    de: 'Mojito',
                    prices: ['3.100 Ft'],
                },
                {
                    hu: 'Strawberry Mojito',
                    en: 'Strawberry Mojito',
                    de: 'Strawberry Mojito',
                    prices: ['3.100 Ft'],
                },
                {
                    hu: 'Moscow Mule',
                    en: 'Moscow Mule',
                    de: 'Moscow Mule',
                    prices: ['3.500 Ft'],
                },
                {
                    hu: 'Bulanga shot (6 db)',
                    en: 'Bulanga shot (6 pcs)',
                    de: 'Bulanga Shot (6 Stk.)',
                    prices: ['3.800 Ft'],
                },
            ],
        },
        {
            hu: 'Gin & Tonic kínálatunk',
            en: 'Our gin & tonic selection',
            de: 'Unsere Gin-&-Tonic-Auswahl',
            images: ['/media/drinks/menu/gin_2.webp'],
            items: [
                {
                    hu: 'Brockmans + Fever Tree Raspberry',
                    en: 'Brockmans + Fever Tree Raspberry',
                    de: 'Brockmans + Fever Tree Raspberry',
                    prices: ['3.400 Ft'],
                },
                {
                    hu: 'Malfy con Limone + Three Cents Pink Grapefruit',
                    en: 'Malfy con Limone + Three Cents Pink Grapefruit',
                    de: 'Malfy con Limone + Three Cents Pink Grapefruit',
                    prices: ['3.400 Ft'],
                },
                {
                    hu: 'Bobbys + Three Cents Dry Tonic',
                    en: 'Bobbys + Three Cents Dry Tonic',
                    de: 'Bobbys + Three Cents Dry Tonic',
                    prices: ['3.400 Ft'],
                },
                {
                    hu: "Hendrick's + Three Cents Aegan Tonic",
                    en: "Hendrick's + Three Cents Aegan Tonic",
                    de: "Hendrick's + Three Cents Aegan Tonic",
                    prices: ['3.400 Ft'],
                },
                {
                    hu: "June by G'Vine + Fever Tree Mediterranean",
                    en: "June by G'Vine + Fever Tree Mediterranean",
                    de: "June by G'Vine + Fever Tree Mediterranean",
                    prices: ['3.400 Ft'],
                },
            ],
        },
        {
            hu: 'Fehér borok',
            en: 'White wines',
            de: 'Weißweine',
            images: ['/media/drinks/menu/bottle_service.webp'],
            items: [
                {
                    hu: 'Cseri - Irsai Olivér (Könnyű és reduktív, tartályban erjedt és röviden érett Irsai. Illatban bodzás, akácvirággal és trópusi gyümölcsökkel kortyban muskotályos jegyekkel, citrusokkal.)',
                    en: 'Cseri - Irsai Olivér (A light, reductive Irsai, tank-fermented and briefly matured. Elderflower on the nose with acacia blossom and tropical fruits; muscatel notes and citrus on the palate.)',
                    de: 'Cseri - Irsai Olivér (Ein leichter, reduktiver Irsai, im Tank vergoren und kurz gereift. In der Nase Holunder, Akazienblüte und tropische Früchte, am Gaumen Muskatnoten und Zitrusfrüchte.)',
                    prices: ['1.450 Ft / 0,15 l', '6.500 Ft / 0,75 l'],
                },
                {
                    hu: 'Béla Bandi - Olaszrizling (Meleg év, korai szüret, gyors éréssel. A szőlő Balatonszőlős idős tőkéiről jött, kézzel válogatva, majd hűtött tartályban erjesztve, egyszerű technológia, hogy a gyümölcs érvényesüljön.)',
                    en: 'Béla Bandi - Olaszrizling (A warm year, early harvest and quick ripening. The grapes come from old vines in Balatonszőlős, hand-selected and fermented in cooled tanks — a simple technology to let the fruit shine.)',
                    de: 'Béla Bandi - Olaszrizling (Ein warmes Jahr, frühe Lese und schnelle Reife. Die Trauben stammen von alten Rebstöcken aus Balatonszőlős, von Hand selektiert und im gekühlten Tank vergoren – eine einfache Technik, damit die Frucht zur Geltung kommt.)',
                    prices: ['1.350 Ft / 0,15 l', '5.600 Ft / 0,75 l'],
                },
                {
                    hu: 'Pannonhalmi Főapátság - Tricollis fehér (A Packalló-, Babszökő-, Tavaszó- és Széldomb-dűlők válogatott terméséből született bor, melynek ízvilágát több különböző szüreti időpont és a dűlők egyéni karaktere határozza meg.)',
                    en: 'Pannonhalmi Főapátság - Tricollis fehér (A wine born from the selected harvest of the Packalló, Babszökő, Tavaszó and Széldomb vineyards; its flavour profile is defined by several different harvest dates and the individual character of the vineyards.)',
                    de: 'Pannonhalmi Főapátság - Tricollis fehér (Ein Wein aus der ausgewählten Ernte der Lagen Packalló, Babszökő, Tavaszó und Széldomb, dessen Aromenwelt von mehreren unterschiedlichen Lesezeitpunkten und dem individuellen Charakter der Lagen geprägt ist.)',
                    prices: ['1.450 Ft / 0,15 l', '6.500 Ft / 0,75 l'],
                },
                {
                    hu: 'Skizo - Sauvignon Blanc (Friss, üde Sauvignon Blanc citrusos és zöldalmás jegyekkel, ropogós savakkal. Könnyű ételek mellé vagy önmagában is ideális.)',
                    en: 'Skizo - Sauvignon Blanc (A fresh, crisp Sauvignon Blanc with citrus and green apple notes and crunchy acidity. Ideal with light dishes or on its own.)',
                    de: 'Skizo - Sauvignon Blanc (Ein frischer, knackiger Sauvignon Blanc mit Zitrus- und Grünapfelnoten und knackiger Säure. Ideal zu leichten Gerichten oder solo.)',
                    prices: ['1.350 Ft / 0,15 l', '5.600 Ft / 0,75 l'],
                },
                {
                    hu: 'Lázár - Chardonnay - Sárgamuskotály (Könnyed, illatos fehérbor Chardonnay és Sárgamuskotály házasításából. Virágos, muskotályos illatát friss gyümölcsös jegyek egészítik ki, ízében pedig harmonikus savak és lágy, elegáns lecsengés érezhető.)',
                    en: 'Lázár - Chardonnay - Sárgamuskotály (A light, fragrant white wine blended from Chardonnay and Sárgamuskotály. Its floral, muscatel nose is complemented by fresh fruity notes, while harmonious acidity and a soft, elegant finish characterize the palate.)',
                    de: 'Lázár - Chardonnay - Sárgamuskotály (Ein leichter, duftiger Weißwein aus der Assemblage von Chardonnay und Sárgamuskotály (Gelber Muskateller). Das blumige, muskatartige Bukett wird von frischen Fruchtnoten ergänzt, am Gaumen zeigen sich harmonische Säure und ein weicher, eleganter Abgang.)',
                    prices: ['1.350 Ft / 0,15 l', '5.600 Ft / 0,75 l'],
                },
                {
                    hu: 'Villa Tolnay - Tenger (Válogatás a pince legszebb hordóiból, négy fajtával. A felét chardonnay, másik felét pedig rajnai, zöldveltelini és olaszrizling adja.)',
                    en: 'Villa Tolnay - Tenger (A selection from the winery’s finest barrels, with four varieties. Half of it is Chardonnay, the other half Rhine Riesling, Grüner Veltliner and Welschriesling.)',
                    de: 'Villa Tolnay - Tenger (Eine Auswahl aus den schönsten Fässern des Weinguts, mit vier Rebsorten. Die eine Hälfte ist Chardonnay, die andere Hälfte Rheinriesling, Grüner Veltliner und Welschriesling.)',
                    prices: ['7.500 Ft / 0,75 l'],
                },
                {
                    hu: 'Figula - Sóskút Olaszrizling (Balatonszőlős, Sóskút dűlő – beszédes név, határozott ásványosság, sós lecsengés. Illatban fehér virágok, alma, körte, keserűmandula, a jól megszokott sós-minerális jelleg.)',
                    en: 'Figula - Sóskút Olaszrizling (Balatonszőlős, Sóskút vineyard – a telling name: pronounced minerality and a salty finish. White flowers, apple, pear and bitter almond on the nose, with the familiar salty-mineral character.)',
                    de: 'Figula - Sóskút Olaszrizling (Balatonszőlős, Lage Sóskút – ein sprechender Name: ausgeprägte Mineralität, salziger Abgang. In der Nase weiße Blüten, Apfel, Birne, Bittermandel und der gewohnte salzig-mineralische Charakter.)',
                    prices: ['8.800 Ft / 0,75 l'],
                },
                {
                    hu: 'Matua - Sauvignon Blanc (Energikus és kristálytiszta illat, benne minden, ami zöld: frissen vágott fű, egres, menta, lime. Az ízben citrusok, grapefruit, minden részletében dinamikus.)',
                    en: 'Matua - Sauvignon Blanc (An energetic, crystal-clear nose with everything green: freshly cut grass, gooseberry, mint and lime. Citrus and grapefruit on the palate; dynamic in every detail.)',
                    de: 'Matua - Sauvignon Blanc (Ein energisches, kristallklares Bukett mit allem, was grün ist: frisch geschnittenes Gras, Stachelbeere, Minze und Limette. Am Gaumen Zitrusfrüchte und Grapefruit, in jedem Detail dynamisch.)',
                    prices: ['12.500 Ft / 0,75 l'],
                },
                {
                    hu: 'Livio Felluga - Sharis (Chardonnay és a Ribolla szőlő fajták házasítása ez az élénksavú fehérbor. Színe világos sárga. Illata intenzíven citrusos, enyhén virágos beütésekkel.)',
                    en: 'Livio Felluga - Sharis (This crisp-acid white wine is a blend of Chardonnay and Ribolla grapes. Its colour is light yellow. Intensely citrusy on the nose with slightly floral undertones.)',
                    de: 'Livio Felluga - Sharis (Dieser Weißwein mit lebendiger Säure ist eine Assemblage der Rebsorten Chardonnay und Ribolla. Er leuchtet hellgelb, mit intensiv zitrischem Duft und leicht blumigen Anklängen.)',
                    prices: ['11.500 Ft / 0,75 l'],
                },
                {
                    hu: 'Livio Felluga - Pinot Grigio (Olaszország egyik legelterjedtebb fehér szőlőfajtája az északi területeken. Illata intenzíven citrusos, lime, grapefruit, enyhén barackos aromával. Szájban enyhén kesernyés mandula ízjegy fedezhető fel.)',
                    en: 'Livio Felluga - Pinot Grigio (One of Italy’s most widespread white grape varieties in the northern regions. Intensely citrusy nose of lime and grapefruit with a slightly peachy aroma. On the palate a faintly bitter almond note emerges.)',
                    de: 'Livio Felluga - Pinot Grigio (Eine der verbreitetsten weißen Rebsorten Italiens in den nördlichen Regionen. Intensiv zitrische Nase mit Limette und Grapefruit sowie leicht pfirsichigen Aromen. Am Gaumen zeigt sich eine leicht bittere Mandelnote.)',
                    prices: ['11.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Grand Tokaj - Furmit (Friss, gyümölcsös, könnyed Tokaji bor, amely modern borászati technológiával készült az egészséges, teljes érésében szüretelt Furmint szőlőfajtából)',
                    en: 'Grand Tokaj - Furmit (A fresh, fruity, light Tokaj wine made with modern winemaking technology from the healthy, fully ripened Furmint grape variety)',
                    de: 'Grand Tokaj - Furmit (Ein frischer, fruchtiger, leichter Tokajer Wein, gekeltert mit moderner Kellertechnik aus der gesunden, vollreif gelesenen Rebsorte Furmint)',
                    prices: ['1.150 Ft / 0,15 l', '4.650 Ft / 0,75 l'],
                },
            ],
        },
        {
            hu: 'Vörös borok',
            en: 'Red wines',
            de: 'Rotweine',
            images: ['/media/drinks/menu/whiskey_2.webp'],
            items: [
                {
                    hu: 'Figula - Simply Red (A Figula család mindennapokra szánt egyszerű, de tartalmas teraszos vöröse.)',
                    en: 'Figula - Simply Red (The Figula family’s simple yet substantial terrace red, made for everyday enjoyment.)',
                    de: 'Figula - Simply Red (Der einfache, aber gehaltvolle Terrassen-Rotwein der Familie Figula, gedacht für jeden Tag.)',
                    prices: ['1.550 Ft / 0,15 l', '6.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Balla - Kolna Kadarka (Nagyon finom erdei gyümölcsös illat, a kadarkára jellemző málna, szamóca, finom fűszerek. A Balla-stílushoz mérten vékonyabb, elegánsabb korty, hosszú lecsengéssel.)',
                    en: 'Balla - Kolna Kadarka (A very fine forest-fruit nose with the raspberry and strawberry typical of Kadarka, plus delicate spices. A sip that is leaner and more elegant than the usual Balla style, with a long finish.)',
                    de: 'Balla - Kolna Kadarka (Sehr feiner Waldfruchtduft mit der für Kadarka typischen Himbeere und Erdbeere sowie feinen Gewürzen. Für den Balla-Stil ein schlankerer, eleganterer Schluck mit langem Abgang.)',
                    prices: ['1.950 Ft / 0,15 l', '8.700 Ft / 0,75 l'],
                },
                {
                    hu: 'Villa Tolnay - Névtelen (10 hónap hordós érlelés, ovális nagy- és francia hordókban. Konyakmeggy, feketeribizli, elegáns fűszeresség, finom savérzet, kiváló egyensúly.)',
                    en: 'Villa Tolnay - Névtelen (10 months of barrel ageing in oval large and French oak barrels. Sour cherry, blackcurrant, elegant spiciness, fine acidity, excellent balance.)',
                    de: 'Villa Tolnay - Névtelen (10 Monate Fassreifung in ovalen Groß- und französischen Fässern. Weichselkirsche, schwarze Johannisbeere, elegante Würze, feine Säure, hervorragende Balance.)',
                    prices: ['1.950 Ft / 0,15 l', '8.700 Ft / 0,75 l'],
                },
                {
                    hu: 'Sauska - Cabernet Sauvignon (A birtokra beérkező szőlőt kíméletes roppantás után héjon áztatták, majd 8 hónapos tartályos és kisebb arányban használt hordós érlelés következett. Megőrizve az elsődleges, gyümölcsös jegyeket, valamint a tüzesebb-fűszeresebb villányi karaktert.)',
                    en: 'Sauska - Cabernet Sauvignon (The grapes arriving at the estate were gently crushed and macerated on the skins, followed by 8 months of ageing in tanks and, to a lesser extent, in used barrels. Preserving the primary, fruity notes as well as the fierier, spicier Villány character.)',
                    de: 'Sauska - Cabernet Sauvignon (Die auf dem Weingut eintreffenden Trauben wurden nach schonendem Quetschen auf der Maische belassen, gefolgt von einer 8-monatigen Reifung im Tank und in geringerem Maße in gebrauchten Fässern. Dabei bleiben die primären, fruchtigen Noten sowie der feurigere, würzigere Villányer Charakter erhalten.)',
                    prices: ['9.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Tormaresca - Primitivo Neprica (8-10 napos tartályos erjedést követően nyolc hónapot érlelődött szintén tartályban, majd forgalomba hozatal előtt négy hónapot pihent palackban. Lágy tanninok, szép savak és édes fűszerek.)',
                    en: 'Tormaresca - Primitivo Neprica (After 8-10 days of tank fermentation it matured for eight months, also in tanks, then rested four months in bottle before release. Soft tannins, fine acidity and sweet spices.)',
                    de: 'Tormaresca - Primitivo Neprica (Nach 8-10 Tagen Gärung im Tank reifte er acht Monate ebenfalls im Tank und ruhte vor der Vermarktung vier Monate in der Flasche. Weiche Tannine, schöne Säure und süße Gewürze.)',
                    prices: ['8.700 Ft / 0,75 l'],
                },
                {
                    hu: 'Perrin - Réserve Cotes du Rhone (Klasszikus Côtes du Rhône, grenache-syrah mourvedre házasítás. Elegáns rubinvörös szín, intenzív piros vörös gyümölcsök illataromája.)',
                    en: 'Perrin - Réserve Cotes du Rhone (A classic Côtes du Rhône, a blend of Grenache, Syrah and Mourvèdre. Elegant ruby-red colour, intense aroma of red berries.)',
                    de: 'Perrin - Réserve Cotes du Rhone (Ein klassischer Côtes du Rhône, Assemblage aus Grenache, Syrah und Mourvèdre. Elegante rubinrote Farbe, intensives Aroma roter Früchte.)',
                    prices: ['9.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Pannonhalmi Főapátság - Infusio (Pannonhalmi vörösbor bordeaux-i stílusban. Merlot és cabernet franc adta presztízsházasítás a legkarakteresebb dűlőből származik. A bor mediterrán jegyekkel tűzdelt, komoly, elegáns és hosszan érlelhető)',
                    en: 'Pannonhalmi Főapátság - Infusio (A Pannonhalma red wine in Bordeaux style. A prestige blend of Merlot and Cabernet Franc from the most characterful vineyard. The wine is studded with Mediterranean notes — serious, elegant and suitable for long ageing.)',
                    de: 'Pannonhalmi Főapátság - Infusio (Ein Pannonhalmer Rotwein im Bordeaux-Stil. Die Prestige-Assemblage aus Merlot und Cabernet Franc stammt aus der charaktervollsten Lage. Der Wein ist mit mediterranen Noten gespickt, ernsthaft, elegant und lange lagerfähig.)',
                    prices: ['20.900 Ft / 0,75 l'],
                },
            ],
        },
        {
            hu: 'Rozé borok',
            en: 'Rose wines',
            de: 'Roséweine',
            images: ['/media/drinks/menu/whiskey_3.webp'],
            items: [
                {
                    hu: 'Laposa - Rosé (Élénk és gazdag ízű kékfrankos rosé a Balaton északi partjáról. Tiszta ízek, ropogós korty, friss savérzet.)',
                    en: 'Laposa - Rosé (A lively and richly flavoured Kékfrankos rosé from the northern shore of Lake Balaton. Pure flavours, a crisp sip and fresh acidity.)',
                    de: 'Laposa - Rosé (Ein lebhafter, gehaltvoller Rosé aus Kékfrankos (Blaufränkisch) vom Nordufer des Balatons. Reine Aromen, knackiger Schluck, frische Säure.)',
                    prices: ['1.150 Ft / 0,15 l', '4.650 Ft / 0,75 l'],
                },
                {
                    hu: 'Béla Bandi - Rosé (Béla és Bandi kékfrankos és merlot házasítása, ahol a gyümölcsök frissessége és a bor karaktere tökéletes egyensúlyban van.)',
                    en: 'Béla Bandi - Rosé (Béla and Bandi’s blend of Kékfrankos and Merlot, where the freshness of the fruit and the character of the wine are in perfect balance.)',
                    de: 'Béla Bandi - Rosé (Bélas und Bandis Assemblage aus Kékfrankos (Blaufränkisch) und Merlot, bei der die Frische der Früchte und der Charakter des Weins in perfekter Balance sind.)',
                    prices: ['1.150 Ft / 0,15 l', '4.650 Ft / 0,75 l'],
                },
                {
                    hu: 'Pannonhalmi Főapátság - Tricollis Rosé (Örök klasszikus, vibráló rózsaszín árnyalattal és friss gyümölcsöket idéző illatokkal. A több szüreti időpont és a három szőlőfajta, kékfrankos, merlot és cabernet franc – házasítása.)',
                    en: 'Pannonhalmi Főapátság - Tricollis Rosé (An everlasting classic with a vibrant pink hue and aromas reminiscent of fresh fruit. A blend of several harvest dates and three grape varieties — Kékfrankos, Merlot and Cabernet Franc.)',
                    de: 'Pannonhalmi Főapátság - Tricollis Rosé (Ein ewiger Klassiker mit lebhaftem Rosa-Ton und Düften, die an frische Früchte erinnern. Eine Assemblage aus mehreren Lesezeitpunkten und drei Rebsorten – Kékfrankos (Blaufränkisch), Merlot und Cabernet Franc.)',
                    prices: ['1.300 Ft / 0,15 l', '5.200 Ft / 0,75 l'],
                },
            ],
        },
        {
            hu: 'Pezsgők',
            en: 'Champagne',
            de: 'Champagner',
            images: ['/media/drinks/menu/bottle_service.webp'],
            items: [
                {
                    hu: 'Hungaria - Irsai Olivér',
                    en: 'Hungaria - Irsai Olivér',
                    de: 'Hungaria - Irsai Olivér',
                    prices: ['1.590 Ft / 0,1 l', '7.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Kreinbacher - Rosé',
                    en: 'Kreinbacher - Rosé',
                    de: 'Kreinbacher - Rosé',
                    prices: ['1.890 Ft / 0,1 l', '12.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Kreinbacher - Brut Classic',
                    en: 'Kreinbacher - Brut Classic',
                    de: 'Kreinbacher - Brut Classic',
                    prices: ['1.890 Ft / 0,1 l', '12.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Veuve Clicquot - Brut',
                    en: 'Veuve Clicquot - Brut',
                    de: 'Veuve Clicquot - Brut',
                    prices: ['47.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Moet Chandon Brut Imperial Magnum',
                    en: 'Moet Chandon Brut Imperial Magnum',
                    de: 'Moet Chandon Brut Imperial Magnum',
                    prices: ['87.900 Ft / 1,5 l'],
                },
                {
                    hu: 'Ruinart R - de Ruinart',
                    en: 'Ruinart R - de Ruinart',
                    de: 'Ruinart R - de Ruinart',
                    prices: ['59.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Deutz - Brut Classic',
                    en: 'Deutz - Brut Classic',
                    de: 'Deutz - Brut Classic',
                    prices: ['47.900 Ft / 0,75 l'],
                },
                {
                    hu: 'Billecart Salmon',
                    en: 'Billecart Salmon',
                    de: 'Billecart Salmon',
                    prices: ['42.900 Ft / 0,75 l'],
                },
            ],
        },
        {
            hu: 'Proseccok',
            en: 'Prosecco',
            de: 'Prosecco',
            images: ['/media/drinks/menu/bottle_service.webp'],
            items: [
                {
                    hu: 'Montelvini Frizzante',
                    en: 'Montelvini Frizzante',
                    de: 'Montelvini Frizzante',
                    prices: ['990 Ft / 0,1 l'],
                },
                {
                    hu: 'Bortolomiol - Miól Extra Dry',
                    en: 'Bortolomiol - Miól Extra Dry',
                    de: 'Bortolomiol - Miól Extra Dry',
                    prices: ['10.900 Ft / 0,75 l'],
                },
                {
                    hu: 'La Tordera - Tittoni',
                    en: 'La Tordera - Tittoni',
                    de: 'La Tordera - Tittoni',
                    prices: ['9.900 Ft / 0,75 l'],
                },
                {
                    hu: "Millesimato Val D' Oca Brut",
                    en: "Millesimato Val D' Oca Brut",
                    de: "Millesimato Val D' Oca Brut",
                    prices: ['10.900 Ft / 0,75 l'],
                },
            ],
        },
    ],
};

export default defineEventHandler(() => drinks);
